openapi: 3.0.0
info:
  version: '2019-12-20'
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=RevokeEndpointAccess API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=RevokeEndpointAccess'
paths:
  /#Action=RevokeEndpointAccess:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: RevokeEndpointAccess
      operationId: GET_RevokeEndpointAccess
      description: Revokes access to a cluster.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointAuthorization'
        '480':
          description: ClusterNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterNotFoundFault'
        '481':
          description: InvalidEndpointStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidEndpointStateFault'
        '482':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
        '483':
          description: EndpointNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointNotFoundFault'
        '484':
          description: EndpointAuthorizationNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointAuthorizationNotFoundFault'
        '485':
          description: InvalidAuthorizationStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidAuthorizationStateFault'
        '486':
          description: InvalidClusterStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterStateFault'
      parameters:
      - name: ClusterIdentifier
        in: query
        required: false
        description: The cluster to revoke access from.
        schema:
          type: string
          maxLength: 2147483647
      - name: Account
        in: query
        required: false
        description: The Amazon Web Services account ID whose access is to be revoked.
        schema:
          type: string
          maxLength: 2147483647
      - name: VpcIds
        in: query
        required: false
        description: The virtual private cloud (VPC) identifiers for which access is to be revoked.
        schema:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/String'
            - xml:
                name: VpcIdentifier
      - name: Force
        in: query
        required: false
        description: Indicates whether to force the revoke action. If true, the Redshift-managed VPC endpoints associated with the endpoint authorization are also deleted.
        schema:
          type: boolean
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - RevokeEndpointAccess
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Revoke Endpoint Access
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=RevokeEndpointAccess'
    post:
      x-aws-operation-name: RevokeEndpointAccess
      operationId: POST_RevokeEndpointAccess
      description: Revokes access to a cluster.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointAuthorization'
        '480':
          description: ClusterNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterNotFoundFault'
        '481':
          description: InvalidEndpointStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidEndpointStateFault'
        '482':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
        '483':
          description: EndpointNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointNotFoundFault'
        '484':
          description: EndpointAuthorizationNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointAuthorizationNotFoundFault'
        '485':
          description: InvalidAuthorizationStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidAuthorizationStateFault'
        '486':
          description: InvalidClusterStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterStateFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/RevokeEndpointAccessMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - RevokeEndpointAccess
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Revoke Endpoint Access
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=RevokeEndpointAccess'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    TStamp:
      type: string
      format: date-time
    Integer:
      type: integer
    String:
      type: string
      maxLength: 2147483647
    EndpointAuthorizationNotFoundFault: {}
    InvalidAuthorizationStateFault: {}
    AuthorizationStatus:
      type: string
      enum:
      - Authorized
      - Revoking
    EndpointNotFoundFault: {}
    InvalidEndpointStateFault: {}
    InvalidClusterStateFault: {}
    RevokeEndpointAccessMessage:
      type: object
      title: RevokeEndpointAccessMessage
      properties:
        ClusterIdentifier:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The cluster to revoke access from.
        Account:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Web Services account ID whose access is to be revoked.
        VpcIds:
          allOf:
          - $ref: '#/components/schemas/VpcIdentifierList'
          - description: The virtual private cloud (VPC) identifiers for which access is to be revoked.
        Force:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: Indicates whether to force the revoke action. If true, the Redshift-managed VPC endpoints associated with the endpoint authorization are also deleted.
    Boolean:
      type: boolean
    InvalidClusterSecurityGroupStateFault: {}
    VpcIdentifierList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/String'
        - xml:
            name: VpcIdentifier
    EndpointAuthorization:
      type: object
      properties:
        Grantor:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Web Services account ID of the cluster owner.
        Grantee:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Web Services account ID of the grantee of the cluster.
        ClusterIdentifier:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The cluster identifier.
        AuthorizeTime:
          allOf:
          - $ref: '#/components/schemas/TStamp'
          - description: The time (UTC) when the authorization was created.
        ClusterStatus:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the cluster.
        Status:
          allOf:
          - $ref: '#/components/schemas/AuthorizationStatus'
          - description: The status of the authorization action.
        AllowedAllVPCs:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: Indicates whether all VPCs in the grantee account are allowed access to the cluster.
        AllowedVPCs:
          allOf:
          - $ref: '#/components/schemas/VpcIdentifierList'
          - description: The VPCs allowed access to the cluster.
        EndpointCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of Redshift-managed VPC endpoints created for the authorization.
      description: Describes an endpoint authorization for authorizing Redshift-managed VPC endpoint access to a cluster across Amazon Web Services accounts.
    ClusterNotFoundFault: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
