openapi: 3.0.0
info:
  version: '2019-12-20'
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=AuthorizeClusterSecurityGroupIngress API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=AuthorizeClusterSecurityGroupIngress'
paths:
  /#Action=AuthorizeClusterSecurityGroupIngress:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: AuthorizeClusterSecurityGroupIngress
      operationId: GET_AuthorizeClusterSecurityGroupIngress
      description: <p>Adds an inbound (ingress) rule to an Amazon Redshift security group. Depending on whether the application accessing your cluster is running on the Internet or an Amazon EC2 instance, you can authorize inbound access to either a Classless Interdomain Routing (CIDR)/Internet Protocol (IP) range or to an Amazon EC2 security group. You can add as many as 20 ingress rules to an Amazon Redshift security group.</p> <p>If you authorize access to an Amazon EC2 security group, specify <i>EC2SecurityGroupName</i> and <i>EC2SecurityGroupOwnerId</i>. The Amazon EC2 security group and Amazon Redshift cluster must be in the same Amazon Web Services Region. </p> <p>If you authorize access to a CIDR/IP address range, specify <i>CIDRIP</i>. For an overview of CIDR blocks, see the Wikipedia article on <a href="http://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing">Classless Inter-Domain Routing</a>. </p> <p>You must also associate the security group with a cluster so that clients running on these IP addresses or the EC2 instance are authorized to connect to the cluster. For information about managing security groups, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-security-groups.html">Working with Security Groups</a> in the <i>Amazon Redshift Cluster Management Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizeClusterSecurityGroupIngressResult'
        '480':
          description: ClusterSecurityGroupNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterSecurityGroupNotFoundFault'
        '481':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
        '482':
          description: AuthorizationAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizationAlreadyExistsFault'
        '483':
          description: AuthorizationQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizationQuotaExceededFault'
      parameters:
      - name: ClusterSecurityGroupName
        in: query
        required: true
        description: The name of the security group to which the ingress rule is added.
        schema:
          type: string
          maxLength: 2147483647
      - name: CIDRIP
        in: query
        required: false
        description: The IP range to be added the Amazon Redshift security group.
        schema:
          type: string
          maxLength: 2147483647
      - name: EC2SecurityGroupName
        in: query
        required: false
        description: The EC2 security group to be added the Amazon Redshift security group.
        schema:
          type: string
          maxLength: 2147483647
      - name: EC2SecurityGroupOwnerId
        in: query
        required: false
        description: '<p>The Amazon Web Services account number of the owner of the security group specified by the <i>EC2SecurityGroupName</i> parameter. The Amazon Web Services Access Key ID is not an acceptable value. </p> <p>Example: <code>111122223333</code> </p>'
        schema:
          type: string
          maxLength: 2147483647
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - AuthorizeClusterSecurityGroupIngress
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Authorize Cluster Security Group Ingress
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=AuthorizeClusterSecurityGroupIngress'
    post:
      x-aws-operation-name: AuthorizeClusterSecurityGroupIngress
      operationId: POST_AuthorizeClusterSecurityGroupIngress
      description: <p>Adds an inbound (ingress) rule to an Amazon Redshift security group. Depending on whether the application accessing your cluster is running on the Internet or an Amazon EC2 instance, you can authorize inbound access to either a Classless Interdomain Routing (CIDR)/Internet Protocol (IP) range or to an Amazon EC2 security group. You can add as many as 20 ingress rules to an Amazon Redshift security group.</p> <p>If you authorize access to an Amazon EC2 security group, specify <i>EC2SecurityGroupName</i> and <i>EC2SecurityGroupOwnerId</i>. The Amazon EC2 security group and Amazon Redshift cluster must be in the same Amazon Web Services Region. </p> <p>If you authorize access to a CIDR/IP address range, specify <i>CIDRIP</i>. For an overview of CIDR blocks, see the Wikipedia article on <a href="http://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing">Classless Inter-Domain Routing</a>. </p> <p>You must also associate the security group with a cluster so that clients running on these IP addresses or the EC2 instance are authorized to connect to the cluster. For information about managing security groups, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-security-groups.html">Working with Security Groups</a> in the <i>Amazon Redshift Cluster Management Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizeClusterSecurityGroupIngressResult'
        '480':
          description: ClusterSecurityGroupNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterSecurityGroupNotFoundFault'
        '481':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
        '482':
          description: AuthorizationAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizationAlreadyExistsFault'
        '483':
          description: AuthorizationQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizationQuotaExceededFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/AuthorizeClusterSecurityGroupIngressMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - AuthorizeClusterSecurityGroupIngress
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Authorize Cluster Security Group Ingress
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=AuthorizeClusterSecurityGroupIngress'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    Tag:
      type: object
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The key, or name, for the resource tag.
        Value:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The value for the resource tag.
      description: A tag consisting of a name/value pair for a resource.
    IPRangeList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/IPRange'
        - xml:
            name: IPRange
    String:
      type: string
      maxLength: 2147483647
    TagList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/Tag'
        - xml:
            name: Tag
    EC2SecurityGroup:
      type: object
      properties:
        Status:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the EC2 security group.
        EC2SecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the EC2 Security Group.
        EC2SecurityGroupOwnerId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The Amazon Web Services account ID of the owner of the EC2 security group specified in the <code>EC2SecurityGroupName</code> field. '
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the EC2 security group.
      description: Describes an Amazon EC2 security group.
    AuthorizeClusterSecurityGroupIngressResult:
      type: object
      properties:
        ClusterSecurityGroup:
          $ref: '#/components/schemas/ClusterSecurityGroup'
    EC2SecurityGroupList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/EC2SecurityGroup'
        - xml:
            name: EC2SecurityGroup
    AuthorizationAlreadyExistsFault: {}
    ClusterSecurityGroupNotFoundFault: {}
    IPRange:
      type: object
      properties:
        Status:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the IP range, for example, "authorized".
        CIDRIP:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The IP range in Classless Inter-Domain Routing (CIDR) notation.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the IP range.
      description: Describes an IP range used in a security group.
    AuthorizationQuotaExceededFault: {}
    ClusterSecurityGroup:
      type: object
      properties:
        ClusterSecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the cluster security group to which the operation was applied.
        Description:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A description of the security group.
        EC2SecurityGroups:
          allOf:
          - $ref: '#/components/schemas/EC2SecurityGroupList'
          - description: A list of EC2 security groups that are permitted to access clusters associated with this cluster security group.
        IPRanges:
          allOf:
          - $ref: '#/components/schemas/IPRangeList'
          - description: A list of IP ranges (CIDR blocks) that are permitted to access clusters associated with this cluster security group.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the cluster security group.
      description: Describes a security group.
    AuthorizeClusterSecurityGroupIngressMessage:
      type: object
      required:
      - ClusterSecurityGroupName
      title: AuthorizeClusterSecurityGroupIngressMessage
      properties:
        ClusterSecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the security group to which the ingress rule is added.
        CIDRIP:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The IP range to be added the Amazon Redshift security group.
        EC2SecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The EC2 security group to be added the Amazon Redshift security group.
        EC2SecurityGroupOwnerId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p>The Amazon Web Services account number of the owner of the security group specified by the <i>EC2SecurityGroupName</i> parameter. The Amazon Web Services Access Key ID is not an acceptable value. </p> <p>Example: <code>111122223333</code> </p>'
      description: <p/>
    InvalidClusterSecurityGroupStateFault: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
