openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=CreateSnapshotCopyGrant #Action=Create Snapshot Copy Grant API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=CreateSnapshotCopyGrant'
paths:
  /#Action=CreateSnapshotCopyGrant:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: CreateSnapshotCopyGrant
      operationId: GET_CreateSnapshotCopyGrant
      description: <p>Creates a snapshot copy grant that permits Amazon Redshift to use an encrypted symmetric key from Key Management Service (KMS) to encrypt copied snapshots in a destination region.</p> <p> For more information about managing snapshot copy grants, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-db-encryption.html">Amazon Redshift Database Encryption</a> in the <i>Amazon Redshift Cluster Management Guide</i>. </p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/CreateSnapshotCopyGrantResult'
        '480':
          description: SnapshotCopyGrantAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/SnapshotCopyGrantAlreadyExistsFault'
        '481':
          description: SnapshotCopyGrantQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/SnapshotCopyGrantQuotaExceededFault'
        '482':
          description: LimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/LimitExceededFault'
        '483':
          description: TagLimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/TagLimitExceededFault'
        '484':
          description: InvalidTagFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidTagFault'
        '485':
          description: DependentServiceRequestThrottlingFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/DependentServiceRequestThrottlingFault'
      parameters:
      - name: SnapshotCopyGrantName
        in: query
        required: true
        description: <p>The name of the snapshot copy grant. This name must be unique in the region for the Amazon Web Services account.</p> <p>Constraints:</p> <ul> <li> <p>Must contain from 1 to 63 alphanumeric characters or hyphens.</p> </li> <li> <p>Alphabetic characters must be lowercase.</p> </li> <li> <p>First character must be a letter.</p> </li> <li> <p>Cannot end with a hyphen or contain two consecutive hyphens.</p> </li> <li> <p>Must be unique for all clusters within an Amazon Web Services account.</p> </li> </ul>
        schema:
          type: string
          maxLength: 2147483647
      - name: KmsKeyId
        in: query
        required: false
        description: The unique identifier of the encrypted symmetric key to which to grant Amazon Redshift permission. If no key is specified, the default key is used.
        schema:
          type: string
          maxLength: 2147483647
      - name: Tags
        in: query
        required: false
        description: A list of tag instances.
        schema:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Tag'
            - xml:
                name: Tag
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - CreateSnapshotCopyGrant
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Create Snapshot Copy Grant
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=CreateSnapshotCopyGrant'
    post:
      x-aws-operation-name: CreateSnapshotCopyGrant
      operationId: POST_CreateSnapshotCopyGrant
      description: <p>Creates a snapshot copy grant that permits Amazon Redshift to use an encrypted symmetric key from Key Management Service (KMS) to encrypt copied snapshots in a destination region.</p> <p> For more information about managing snapshot copy grants, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-db-encryption.html">Amazon Redshift Database Encryption</a> in the <i>Amazon Redshift Cluster Management Guide</i>. </p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/CreateSnapshotCopyGrantResult'
        '480':
          description: SnapshotCopyGrantAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/SnapshotCopyGrantAlreadyExistsFault'
        '481':
          description: SnapshotCopyGrantQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/SnapshotCopyGrantQuotaExceededFault'
        '482':
          description: LimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/LimitExceededFault'
        '483':
          description: TagLimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/TagLimitExceededFault'
        '484':
          description: InvalidTagFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidTagFault'
        '485':
          description: DependentServiceRequestThrottlingFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/DependentServiceRequestThrottlingFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/CreateSnapshotCopyGrantMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - CreateSnapshotCopyGrant
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Create Snapshot Copy Grant
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=CreateSnapshotCopyGrant'
components:
  schemas:
    SnapshotCopyGrantAlreadyExistsFault: {}
    DependentServiceRequestThrottlingFault: {}
    TagList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/Tag'
        - xml:
            name: Tag
    Tag:
      type: object
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The key, or name, for the resource tag.
        Value:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The value for the resource tag.
      description: A tag consisting of a name/value pair for a resource.
    TagLimitExceededFault: {}
    SnapshotCopyGrantQuotaExceededFault: {}
    LimitExceededFault: {}
    SnapshotCopyGrant:
      type: object
      properties:
        SnapshotCopyGrantName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the snapshot copy grant.
        KmsKeyId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The unique identifier of the encrypted symmetric key in Amazon Web Services KMS to which Amazon Redshift is granted permission.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: A list of tag instances.
      description: <p>The snapshot copy grant that grants Amazon Redshift permission to encrypt copied snapshots with the specified encrypted symmetric key from Amazon Web Services KMS in the destination region.</p> <p> For more information about managing snapshot copy grants, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-db-encryption.html">Amazon Redshift Database Encryption</a> in the <i>Amazon Redshift Cluster Management Guide</i>. </p>
    CreateSnapshotCopyGrantMessage:
      type: object
      required:
      - SnapshotCopyGrantName
      title: CreateSnapshotCopyGrantMessage
      properties:
        SnapshotCopyGrantName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>The name of the snapshot copy grant. This name must be unique in the region for the Amazon Web Services account.</p> <p>Constraints:</p> <ul> <li> <p>Must contain from 1 to 63 alphanumeric characters or hyphens.</p> </li> <li> <p>Alphabetic characters must be lowercase.</p> </li> <li> <p>First character must be a letter.</p> </li> <li> <p>Cannot end with a hyphen or contain two consecutive hyphens.</p> </li> <li> <p>Must be unique for all clusters within an Amazon Web Services account.</p> </li> </ul>
        KmsKeyId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The unique identifier of the encrypted symmetric key to which to grant Amazon Redshift permission. If no key is specified, the default key is used.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: A list of tag instances.
      description: The result of the <code>CreateSnapshotCopyGrant</code> action.
    InvalidTagFault: {}
    String:
      type: string
      maxLength: 2147483647
    CreateSnapshotCopyGrantResult:
      type: object
      properties:
        SnapshotCopyGrant:
          $ref: '#/components/schemas/SnapshotCopyGrant'
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
