openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=CreateClusterParameterGroup API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=CreateClusterParameterGroup'
paths:
  /#Action=CreateClusterParameterGroup:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: CreateClusterParameterGroup
      operationId: GET_CreateClusterParameterGroup
      description: <p>Creates an Amazon Redshift parameter group.</p> <p>Creating parameter groups is independent of creating clusters. You can associate a cluster with a parameter group when you create the cluster. You can also associate an existing cluster with a parameter group after the cluster is created by using <a>ModifyCluster</a>. </p> <p>Parameters in the parameter group define specific behavior that applies to the databases you create on the cluster. For more information about parameters and parameter groups, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-parameter-groups.html">Amazon Redshift Parameter Groups</a> in the <i>Amazon Redshift Cluster Management Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/CreateClusterParameterGroupResult'
        '480':
          description: ClusterParameterGroupQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterParameterGroupQuotaExceededFault'
        '481':
          description: ClusterParameterGroupAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterParameterGroupAlreadyExistsFault'
        '482':
          description: TagLimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/TagLimitExceededFault'
        '483':
          description: InvalidTagFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidTagFault'
      parameters:
      - name: ParameterGroupName
        in: query
        required: true
        description: <p>The name of the cluster parameter group.</p> <p>Constraints:</p> <ul> <li> <p>Must be 1 to 255 alphanumeric characters or hyphens</p> </li> <li> <p>First character must be a letter.</p> </li> <li> <p>Cannot end with a hyphen or contain two consecutive hyphens.</p> </li> <li> <p>Must be unique withing your Amazon Web Services account.</p> </li> </ul> <note> <p>This value is stored as a lower-case string.</p> </note>
        schema:
          type: string
          maxLength: 2147483647
      - name: ParameterGroupFamily
        in: query
        required: true
        description: <p>The Amazon Redshift engine version to which the cluster parameter group applies. The cluster engine version determines the set of parameters.</p> <p>To get a list of valid parameter group family names, you can call <a>DescribeClusterParameterGroups</a>. By default, Amazon Redshift returns a list of all the parameter groups that are owned by your Amazon Web Services account, including the default parameter groups for each Amazon Redshift engine version. The parameter group family names associated with the default parameter groups provide you the valid values. For example, a valid family name is "redshift-1.0". </p>
        schema:
          type: string
          maxLength: 2147483647
      - name: Description
        in: query
        required: true
        description: A description of the parameter group.
        schema:
          type: string
          maxLength: 2147483647
      - name: Tags
        in: query
        required: false
        description: A list of tag instances.
        schema:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Tag'
            - xml:
                name: Tag
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - CreateClusterParameterGroup
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Create Cluster Parameter Group
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=CreateClusterParameterGroup'
    post:
      x-aws-operation-name: CreateClusterParameterGroup
      operationId: POST_CreateClusterParameterGroup
      description: <p>Creates an Amazon Redshift parameter group.</p> <p>Creating parameter groups is independent of creating clusters. You can associate a cluster with a parameter group when you create the cluster. You can also associate an existing cluster with a parameter group after the cluster is created by using <a>ModifyCluster</a>. </p> <p>Parameters in the parameter group define specific behavior that applies to the databases you create on the cluster. For more information about parameters and parameter groups, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-parameter-groups.html">Amazon Redshift Parameter Groups</a> in the <i>Amazon Redshift Cluster Management Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/CreateClusterParameterGroupResult'
        '480':
          description: ClusterParameterGroupQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterParameterGroupQuotaExceededFault'
        '481':
          description: ClusterParameterGroupAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterParameterGroupAlreadyExistsFault'
        '482':
          description: TagLimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/TagLimitExceededFault'
        '483':
          description: InvalidTagFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidTagFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/CreateClusterParameterGroupMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - CreateClusterParameterGroup
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Create Cluster Parameter Group
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=CreateClusterParameterGroup'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    ClusterParameterGroupQuotaExceededFault: {}
    ClusterParameterGroup:
      type: object
      properties:
        ParameterGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the cluster parameter group.
        ParameterGroupFamily:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the cluster parameter group family that this cluster parameter group is compatible with.
        Description:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The description of the parameter group.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the cluster parameter group.
      description: Describes a parameter group.
    TagLimitExceededFault: {}
    Tag:
      type: object
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The key, or name, for the resource tag.
        Value:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The value for the resource tag.
      description: A tag consisting of a name/value pair for a resource.
    ClusterParameterGroupAlreadyExistsFault: {}
    InvalidTagFault: {}
    CreateClusterParameterGroupMessage:
      type: object
      required:
      - ParameterGroupName
      - ParameterGroupFamily
      - Description
      title: CreateClusterParameterGroupMessage
      properties:
        ParameterGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>The name of the cluster parameter group.</p> <p>Constraints:</p> <ul> <li> <p>Must be 1 to 255 alphanumeric characters or hyphens</p> </li> <li> <p>First character must be a letter.</p> </li> <li> <p>Cannot end with a hyphen or contain two consecutive hyphens.</p> </li> <li> <p>Must be unique withing your Amazon Web Services account.</p> </li> </ul> <note> <p>This value is stored as a lower-case string.</p> </note>
        ParameterGroupFamily:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>The Amazon Redshift engine version to which the cluster parameter group applies. The cluster engine version determines the set of parameters.</p> <p>To get a list of valid parameter group family names, you can call <a>DescribeClusterParameterGroups</a>. By default, Amazon Redshift returns a list of all the parameter groups that are owned by your Amazon Web Services account, including the default parameter groups for each Amazon Redshift engine version. The parameter group family names associated with the default parameter groups provide you the valid values. For example, a valid family name is "redshift-1.0". </p>
        Description:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A description of the parameter group.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: A list of tag instances.
      description: <p/>
    CreateClusterParameterGroupResult:
      type: object
      properties:
        ClusterParameterGroup:
          $ref: '#/components/schemas/ClusterParameterGroup'
    String:
      type: string
      maxLength: 2147483647
    TagList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/Tag'
        - xml:
            name: Tag
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
