openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=RevokeClusterSecurityGroupIngress #Action=Revoke Cluster Security Group Ingress API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=RevokeClusterSecurityGroupIngress'
paths:
  /#Action=RevokeClusterSecurityGroupIngress:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: RevokeClusterSecurityGroupIngress
      operationId: GET_RevokeClusterSecurityGroupIngress
      description: 'Revokes an ingress rule in an Amazon Redshift security group for a previously authorized IP range or Amazon EC2 security group. To add an ingress rule, see <a>AuthorizeClusterSecurityGroupIngress</a>. For information about managing security groups, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-security-groups.html">Amazon Redshift Cluster Security Groups</a> in the <i>Amazon Redshift Cluster Management Guide</i>. '
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/RevokeClusterSecurityGroupIngressResult'
        '480':
          description: ClusterSecurityGroupNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterSecurityGroupNotFoundFault'
        '481':
          description: AuthorizationNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizationNotFoundFault'
        '482':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
      parameters:
      - name: ClusterSecurityGroupName
        in: query
        required: true
        description: The name of the security Group from which to revoke the ingress rule.
        schema:
          type: string
          maxLength: 2147483647
      - name: CIDRIP
        in: query
        required: false
        description: 'The IP range for which to revoke access. This range must be a valid Classless Inter-Domain Routing (CIDR) block of IP addresses. If <code>CIDRIP</code> is specified, <code>EC2SecurityGroupName</code> and <code>EC2SecurityGroupOwnerId</code> cannot be provided. '
        schema:
          type: string
          maxLength: 2147483647
      - name: EC2SecurityGroupName
        in: query
        required: false
        description: 'The name of the EC2 Security Group whose access is to be revoked. If <code>EC2SecurityGroupName</code> is specified, <code>EC2SecurityGroupOwnerId</code> must also be provided and <code>CIDRIP</code> cannot be provided. '
        schema:
          type: string
          maxLength: 2147483647
      - name: EC2SecurityGroupOwnerId
        in: query
        required: false
        description: '<p>The Amazon Web Services account number of the owner of the security group specified in the <code>EC2SecurityGroupName</code> parameter. The Amazon Web Services access key ID is not an acceptable value. If <code>EC2SecurityGroupOwnerId</code> is specified, <code>EC2SecurityGroupName</code> must also be provided. and <code>CIDRIP</code> cannot be provided. </p> <p>Example: <code>111122223333</code> </p>'
        schema:
          type: string
          maxLength: 2147483647
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - RevokeClusterSecurityGroupIngress
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Revoke Cluster Security Group Ingress
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=RevokeClusterSecurityGroupIngress'
    post:
      x-aws-operation-name: RevokeClusterSecurityGroupIngress
      operationId: POST_RevokeClusterSecurityGroupIngress
      description: 'Revokes an ingress rule in an Amazon Redshift security group for a previously authorized IP range or Amazon EC2 security group. To add an ingress rule, see <a>AuthorizeClusterSecurityGroupIngress</a>. For information about managing security groups, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-security-groups.html">Amazon Redshift Cluster Security Groups</a> in the <i>Amazon Redshift Cluster Management Guide</i>. '
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/RevokeClusterSecurityGroupIngressResult'
        '480':
          description: ClusterSecurityGroupNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterSecurityGroupNotFoundFault'
        '481':
          description: AuthorizationNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/AuthorizationNotFoundFault'
        '482':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/RevokeClusterSecurityGroupIngressMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - RevokeClusterSecurityGroupIngress
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Revoke Cluster Security Group Ingress
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=RevokeClusterSecurityGroupIngress'
components:
  schemas:
    TagList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/Tag'
        - xml:
            name: Tag
    EC2SecurityGroupList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/EC2SecurityGroup'
        - xml:
            name: EC2SecurityGroup
    IPRange:
      type: object
      properties:
        Status:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the IP range, for example, "authorized".
        CIDRIP:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The IP range in Classless Inter-Domain Routing (CIDR) notation.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the IP range.
      description: Describes an IP range used in a security group.
    IPRangeList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/IPRange'
        - xml:
            name: IPRange
    RevokeClusterSecurityGroupIngressMessage:
      type: object
      required:
      - ClusterSecurityGroupName
      title: RevokeClusterSecurityGroupIngressMessage
      properties:
        ClusterSecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the security Group from which to revoke the ingress rule.
        CIDRIP:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The IP range for which to revoke access. This range must be a valid Classless Inter-Domain Routing (CIDR) block of IP addresses. If <code>CIDRIP</code> is specified, <code>EC2SecurityGroupName</code> and <code>EC2SecurityGroupOwnerId</code> cannot be provided. '
        EC2SecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The name of the EC2 Security Group whose access is to be revoked. If <code>EC2SecurityGroupName</code> is specified, <code>EC2SecurityGroupOwnerId</code> must also be provided and <code>CIDRIP</code> cannot be provided. '
        EC2SecurityGroupOwnerId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p>The Amazon Web Services account number of the owner of the security group specified in the <code>EC2SecurityGroupName</code> parameter. The Amazon Web Services access key ID is not an acceptable value. If <code>EC2SecurityGroupOwnerId</code> is specified, <code>EC2SecurityGroupName</code> must also be provided. and <code>CIDRIP</code> cannot be provided. </p> <p>Example: <code>111122223333</code> </p>'
      description: <p/>
    Tag:
      type: object
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The key, or name, for the resource tag.
        Value:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The value for the resource tag.
      description: A tag consisting of a name/value pair for a resource.
    EC2SecurityGroup:
      type: object
      properties:
        Status:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the EC2 security group.
        EC2SecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the EC2 Security Group.
        EC2SecurityGroupOwnerId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The Amazon Web Services account ID of the owner of the EC2 security group specified in the <code>EC2SecurityGroupName</code> field. '
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the EC2 security group.
      description: Describes an Amazon EC2 security group.
    ClusterSecurityGroup:
      type: object
      properties:
        ClusterSecurityGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the cluster security group to which the operation was applied.
        Description:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A description of the security group.
        EC2SecurityGroups:
          allOf:
          - $ref: '#/components/schemas/EC2SecurityGroupList'
          - description: A list of EC2 security groups that are permitted to access clusters associated with this cluster security group.
        IPRanges:
          allOf:
          - $ref: '#/components/schemas/IPRangeList'
          - description: A list of IP ranges (CIDR blocks) that are permitted to access clusters associated with this cluster security group.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the cluster security group.
      description: Describes a security group.
    RevokeClusterSecurityGroupIngressResult:
      type: object
      properties:
        ClusterSecurityGroup:
          $ref: '#/components/schemas/ClusterSecurityGroup'
    String:
      type: string
      maxLength: 2147483647
    ClusterSecurityGroupNotFoundFault: {}
    InvalidClusterSecurityGroupStateFault: {}
    AuthorizationNotFoundFault: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
