openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=DeleteEndpointAccess API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=DeleteEndpointAccess'
paths:
  /#Action=DeleteEndpointAccess:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: DeleteEndpointAccess
      operationId: GET_DeleteEndpointAccess
      description: Deletes a Redshift-managed VPC endpoint.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointAccess'
        '480':
          description: ClusterNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterNotFoundFault'
        '481':
          description: InvalidEndpointStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidEndpointStateFault'
        '482':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
        '483':
          description: EndpointNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointNotFoundFault'
        '484':
          description: InvalidClusterStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterStateFault'
      parameters:
      - name: EndpointName
        in: query
        required: true
        description: The Redshift-managed VPC endpoint to delete.
        schema:
          type: string
          maxLength: 2147483647
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DeleteEndpointAccess
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Delete Endpoint Access
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DeleteEndpointAccess'
    post:
      x-aws-operation-name: DeleteEndpointAccess
      operationId: POST_DeleteEndpointAccess
      description: Deletes a Redshift-managed VPC endpoint.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointAccess'
        '480':
          description: ClusterNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterNotFoundFault'
        '481':
          description: InvalidEndpointStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidEndpointStateFault'
        '482':
          description: InvalidClusterSecurityGroupStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterSecurityGroupStateFault'
        '483':
          description: EndpointNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/EndpointNotFoundFault'
        '484':
          description: InvalidClusterStateFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidClusterStateFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/DeleteEndpointAccessMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DeleteEndpointAccess
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Delete Endpoint Access
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DeleteEndpointAccess'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    NetworkInterface:
      type: object
      properties:
        NetworkInterfaceId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The network interface identifier. '
        SubnetId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The subnet identifier. '
        PrivateIpAddress:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The IPv4 address of the network interface within the subnet. '
        AvailabilityZone:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The Availability Zone. '
      description: 'Describes a network interface. '
    TStamp:
      type: string
      format: date-time
    Integer:
      type: integer
    String:
      type: string
      maxLength: 2147483647
    EndpointAccess:
      type: object
      properties:
        ClusterIdentifier:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The cluster identifier of the cluster associated with the endpoint.
        ResourceOwner:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Amazon Web Services account ID of the owner of the cluster.
        SubnetGroupName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The subnet group name where Amazon Redshift chooses to deploy the endpoint.
        EndpointStatus:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the endpoint.
        EndpointName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the endpoint.
        EndpointCreateTime:
          allOf:
          - $ref: '#/components/schemas/TStamp'
          - description: The time (UTC) that the endpoint was created.
        Port:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The port number on which the cluster accepts incoming connections.
        Address:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The DNS address of the endpoint.
        VpcSecurityGroups:
          allOf:
          - $ref: '#/components/schemas/VpcSecurityGroupMembershipList'
          - description: The security groups associated with the endpoint.
        VpcEndpoint:
          $ref: '#/components/schemas/VpcEndpoint'
      description: Describes a Redshift-managed VPC endpoint.
    EndpointNotFoundFault: {}
    InvalidEndpointStateFault: {}
    NetworkInterfaceList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/NetworkInterface'
        - xml:
            name: NetworkInterface
    InvalidClusterStateFault: {}
    VpcEndpoint:
      type: object
      properties:
        VpcEndpointId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The connection endpoint ID for connecting an Amazon Redshift cluster through the proxy.
        VpcId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The VPC identifier that the endpoint is associated. '
        NetworkInterfaces:
          allOf:
          - $ref: '#/components/schemas/NetworkInterfaceList'
          - description: 'One or more network interfaces of the endpoint. Also known as an interface endpoint. '
      description: The connection endpoint for connecting to an Amazon Redshift cluster through the proxy.
    VpcSecurityGroupMembership:
      type: object
      properties:
        VpcSecurityGroupId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The identifier of the VPC security group.
        Status:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The status of the VPC security group.
      description: Describes the members of a VPC security group.
    InvalidClusterSecurityGroupStateFault: {}
    VpcSecurityGroupMembershipList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/VpcSecurityGroupMembership'
        - xml:
            name: VpcSecurityGroup
    ClusterNotFoundFault: {}
    DeleteEndpointAccessMessage:
      type: object
      required:
      - EndpointName
      title: DeleteEndpointAccessMessage
      properties:
        EndpointName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The Redshift-managed VPC endpoint to delete.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
