openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=DescribeReservedNodes #Action=Describe Reserved Nodes API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=DescribeReservedNodes'
paths:
  /#Action=DescribeReservedNodes:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: DescribeReservedNodes
      operationId: GET_DescribeReservedNodes
      description: Returns the descriptions of the reserved nodes.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodesMessage'
        '480':
          description: ReservedNodeNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeNotFoundFault'
        '481':
          description: DependentServiceUnavailableFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/DependentServiceUnavailableFault'
      parameters:
      - name: ReservedNodeId
        in: query
        required: false
        description: Identifier for the node reservation.
        schema:
          type: string
          maxLength: 2147483647
      - name: MaxRecords
        in: query
        required: false
        description: '<p>The maximum number of response records to return in each call. If the number of remaining response records exceeds the specified <code>MaxRecords</code> value, a value is returned in a <code>marker</code> field of the response. You can retrieve the next set of records by retrying the command with the returned marker value. </p> <p>Default: <code>100</code> </p> <p>Constraints: minimum 20, maximum 100.</p>'
        schema:
          type: integer
      - name: Marker
        in: query
        required: false
        description: 'An optional parameter that specifies the starting point to return a set of response records. When the results of a <a>DescribeReservedNodes</a> request exceed the value specified in <code>MaxRecords</code>, Amazon Web Services returns a value in the <code>Marker</code> field of the response. You can retrieve the next set of response records by providing the returned marker value in the <code>Marker</code> parameter and retrying the request. '
        schema:
          type: string
          maxLength: 2147483647
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DescribeReservedNodes
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Describe Reserved Nodes
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DescribeReservedNodes'
    post:
      x-aws-operation-name: DescribeReservedNodes
      operationId: POST_DescribeReservedNodes
      description: Returns the descriptions of the reserved nodes.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodesMessage'
        '480':
          description: ReservedNodeNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeNotFoundFault'
        '481':
          description: DependentServiceUnavailableFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/DependentServiceUnavailableFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/DescribeReservedNodesMessage'
      parameters:
      - name: MaxRecords
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: Marker
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DescribeReservedNodes
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Describe Reserved Nodes
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DescribeReservedNodes'
components:
  schemas:
    Integer:
      type: integer
    RecurringChargeList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/RecurringCharge'
        - xml:
            name: RecurringCharge
    ReservedNodeList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/ReservedNode'
        - xml:
            name: ReservedNode
    DescribeReservedNodesMessage:
      type: object
      title: DescribeReservedNodesMessage
      properties:
        ReservedNodeId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Identifier for the node reservation.
        MaxRecords:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: '<p>The maximum number of response records to return in each call. If the number of remaining response records exceeds the specified <code>MaxRecords</code> value, a value is returned in a <code>marker</code> field of the response. You can retrieve the next set of records by retrying the command with the returned marker value. </p> <p>Default: <code>100</code> </p> <p>Constraints: minimum 20, maximum 100.</p>'
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'An optional parameter that specifies the starting point to return a set of response records. When the results of a <a>DescribeReservedNodes</a> request exceed the value specified in <code>MaxRecords</code>, Amazon Web Services returns a value in the <code>Marker</code> field of the response. You can retrieve the next set of response records by providing the returned marker value in the <code>Marker</code> parameter and retrying the request. '
      description: <p/>
    ReservedNode:
      type: object
      properties:
        ReservedNodeId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The unique identifier for the reservation.
        ReservedNodeOfferingId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The identifier for the reserved node offering.
        NodeType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The node type of the reserved node.
        StartTime:
          allOf:
          - $ref: '#/components/schemas/TStamp'
          - description: The time the reservation started. You purchase a reserved node offering for a duration. This is the start time of that duration.
        Duration:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The duration of the node reservation in seconds.
        FixedPrice:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The fixed cost Amazon Redshift charges you for this reserved node.
        UsagePrice:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The hourly rate Amazon Redshift charges you for this reserved node.
        CurrencyCode:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The currency code for the reserved cluster.
        NodeCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of reserved compute nodes.
        State:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>The state of the reserved compute node.</p> <p>Possible Values:</p> <ul> <li> <p>pending-payment-This reserved node has recently been purchased, and the sale has been approved, but payment has not yet been confirmed.</p> </li> <li> <p>active-This reserved node is owned by the caller and is available for use.</p> </li> <li> <p>payment-failed-Payment failed for the purchase attempt.</p> </li> <li> <p>retired-The reserved node is no longer available. </p> </li> <li> <p>exchanging-The owner is exchanging the reserved node for another reserved node.</p> </li> </ul>
        OfferingType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The anticipated utilization of the reserved node, as defined in the reserved node offering.
        RecurringCharges:
          allOf:
          - $ref: '#/components/schemas/RecurringChargeList'
          - description: The recurring charges for the reserved node.
        ReservedNodeOfferingType:
          allOf:
          - $ref: '#/components/schemas/ReservedNodeOfferingType'
          - description: <p/>
      description: 'Describes a reserved node. You can call the <a>DescribeReservedNodeOfferings</a> API to obtain the available reserved node offerings. '
    TStamp:
      type: string
      format: date-time
    ReservedNodesMessage:
      type: object
      properties:
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'A value that indicates the starting point for the next set of response records in a subsequent request. If a value is returned in a response, you can retrieve the next set of records by providing this returned marker value in the <code>Marker</code> parameter and retrying the command. If the <code>Marker</code> field is empty, all response records have been retrieved for the request. '
        ReservedNodes:
          allOf:
          - $ref: '#/components/schemas/ReservedNodeList'
          - description: The list of <code>ReservedNode</code> objects.
      description: <p/>
    ReservedNodeOfferingType:
      type: string
      enum:
      - Regular
      - Upgradable
    ReservedNodeNotFoundFault: {}
    RecurringCharge:
      type: object
      properties:
        RecurringChargeAmount:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The amount charged per the period of time specified by the recurring charge frequency.
        RecurringChargeFrequency:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The frequency at which the recurring charge amount is applied.
      description: Describes a recurring charge.
    String:
      type: string
      maxLength: 2147483647
    IntegerOptional:
      type: integer
    Double:
      type: number
      format: double
    DependentServiceUnavailableFault: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
