openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=PurchaseReservedNodeOffering API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=PurchaseReservedNodeOffering'
paths:
  /#Action=PurchaseReservedNodeOffering:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: PurchaseReservedNodeOffering
      operationId: GET_PurchaseReservedNodeOffering
      description: <p>Allows you to purchase reserved nodes. Amazon Redshift offers a predefined set of reserved node offerings. You can purchase one or more of the offerings. You can call the <a>DescribeReservedNodeOfferings</a> API to obtain the available reserved node offerings. You can call this API by providing a specific reserved node offering and the number of nodes you want to reserve. </p> <p> For more information about reserved node offerings, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/purchase-reserved-node-instance.html">Purchasing Reserved Nodes</a> in the <i>Amazon Redshift Cluster Management Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/PurchaseReservedNodeOfferingResult'
        '480':
          description: ReservedNodeOfferingNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeOfferingNotFoundFault'
        '481':
          description: ReservedNodeAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeAlreadyExistsFault'
        '482':
          description: ReservedNodeQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeQuotaExceededFault'
        '483':
          description: UnsupportedOperationFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/UnsupportedOperationFault'
      parameters:
      - name: ReservedNodeOfferingId
        in: query
        required: true
        description: The unique identifier of the reserved node offering you want to purchase.
        schema:
          type: string
          maxLength: 2147483647
      - name: NodeCount
        in: query
        required: false
        description: '<p>The number of reserved nodes that you want to purchase.</p> <p>Default: <code>1</code> </p>'
        schema:
          type: integer
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - PurchaseReservedNodeOffering
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Purchase Reserved Node Offering
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=PurchaseReservedNodeOffering'
    post:
      x-aws-operation-name: PurchaseReservedNodeOffering
      operationId: POST_PurchaseReservedNodeOffering
      description: <p>Allows you to purchase reserved nodes. Amazon Redshift offers a predefined set of reserved node offerings. You can purchase one or more of the offerings. You can call the <a>DescribeReservedNodeOfferings</a> API to obtain the available reserved node offerings. You can call this API by providing a specific reserved node offering and the number of nodes you want to reserve. </p> <p> For more information about reserved node offerings, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/purchase-reserved-node-instance.html">Purchasing Reserved Nodes</a> in the <i>Amazon Redshift Cluster Management Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/PurchaseReservedNodeOfferingResult'
        '480':
          description: ReservedNodeOfferingNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeOfferingNotFoundFault'
        '481':
          description: ReservedNodeAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeAlreadyExistsFault'
        '482':
          description: ReservedNodeQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ReservedNodeQuotaExceededFault'
        '483':
          description: UnsupportedOperationFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/UnsupportedOperationFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/PurchaseReservedNodeOfferingMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - PurchaseReservedNodeOffering
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Purchase Reserved Node Offering
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=PurchaseReservedNodeOffering'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    TStamp:
      type: string
      format: date-time
    Double:
      type: number
      format: double
    ReservedNodeQuotaExceededFault: {}
    RecurringCharge:
      type: object
      properties:
        RecurringChargeAmount:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The amount charged per the period of time specified by the recurring charge frequency.
        RecurringChargeFrequency:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The frequency at which the recurring charge amount is applied.
      description: Describes a recurring charge.
    ReservedNodeOfferingType:
      type: string
      enum:
      - Regular
      - Upgradable
    Integer:
      type: integer
    String:
      type: string
      maxLength: 2147483647
    PurchaseReservedNodeOfferingResult:
      type: object
      properties:
        ReservedNode:
          $ref: '#/components/schemas/ReservedNode'
    PurchaseReservedNodeOfferingMessage:
      type: object
      required:
      - ReservedNodeOfferingId
      title: PurchaseReservedNodeOfferingMessage
      properties:
        ReservedNodeOfferingId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The unique identifier of the reserved node offering you want to purchase.
        NodeCount:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: '<p>The number of reserved nodes that you want to purchase.</p> <p>Default: <code>1</code> </p>'
      description: <p/>
    ReservedNodeOfferingNotFoundFault: {}
    RecurringChargeList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/RecurringCharge'
        - xml:
            name: RecurringCharge
    ReservedNodeAlreadyExistsFault: {}
    ReservedNode:
      type: object
      properties:
        ReservedNodeId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The unique identifier for the reservation.
        ReservedNodeOfferingId:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The identifier for the reserved node offering.
        NodeType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The node type of the reserved node.
        StartTime:
          allOf:
          - $ref: '#/components/schemas/TStamp'
          - description: The time the reservation started. You purchase a reserved node offering for a duration. This is the start time of that duration.
        Duration:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The duration of the node reservation in seconds.
        FixedPrice:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The fixed cost Amazon Redshift charges you for this reserved node.
        UsagePrice:
          allOf:
          - $ref: '#/components/schemas/Double'
          - description: The hourly rate Amazon Redshift charges you for this reserved node.
        CurrencyCode:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The currency code for the reserved cluster.
        NodeCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of reserved compute nodes.
        State:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>The state of the reserved compute node.</p> <p>Possible Values:</p> <ul> <li> <p>pending-payment-This reserved node has recently been purchased, and the sale has been approved, but payment has not yet been confirmed.</p> </li> <li> <p>active-This reserved node is owned by the caller and is available for use.</p> </li> <li> <p>payment-failed-Payment failed for the purchase attempt.</p> </li> <li> <p>retired-The reserved node is no longer available. </p> </li> <li> <p>exchanging-The owner is exchanging the reserved node for another reserved node.</p> </li> </ul>
        OfferingType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The anticipated utilization of the reserved node, as defined in the reserved node offering.
        RecurringCharges:
          allOf:
          - $ref: '#/components/schemas/RecurringChargeList'
          - description: The recurring charges for the reserved node.
        ReservedNodeOfferingType:
          allOf:
          - $ref: '#/components/schemas/ReservedNodeOfferingType'
          - description: <p/>
      description: 'Describes a reserved node. You can call the <a>DescribeReservedNodeOfferings</a> API to obtain the available reserved node offerings. '
    IntegerOptional:
      type: integer
    UnsupportedOperationFault: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
