openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=CreateHsmConfiguration #Action=Create Hsm Configuration API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=CreateHsmConfiguration'
paths:
  /#Action=CreateHsmConfiguration:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: CreateHsmConfiguration
      operationId: GET_CreateHsmConfiguration
      description: <p>Creates an HSM configuration that contains the information required by an Amazon Redshift cluster to store and use database encryption keys in a Hardware Security Module (HSM). After creating the HSM configuration, you can specify it as a parameter when creating a cluster. The cluster will then store its encryption keys in the HSM.</p> <p>In addition to creating an HSM configuration, you must also create an HSM client certificate. For more information, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-HSM.html">Hardware Security Modules</a> in the Amazon Redshift Cluster Management Guide.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/CreateHsmConfigurationResult'
        '480':
          description: HsmConfigurationAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/HsmConfigurationAlreadyExistsFault'
        '481':
          description: HsmConfigurationQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/HsmConfigurationQuotaExceededFault'
        '482':
          description: TagLimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/TagLimitExceededFault'
        '483':
          description: InvalidTagFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidTagFault'
      parameters:
      - name: HsmConfigurationIdentifier
        in: query
        required: true
        description: The identifier to be assigned to the new Amazon Redshift HSM configuration.
        schema:
          type: string
          maxLength: 2147483647
      - name: Description
        in: query
        required: true
        description: A text description of the HSM configuration to be created.
        schema:
          type: string
          maxLength: 2147483647
      - name: HsmIpAddress
        in: query
        required: true
        description: The IP address that the Amazon Redshift cluster must use to access the HSM.
        schema:
          type: string
          maxLength: 2147483647
      - name: HsmPartitionName
        in: query
        required: true
        description: The name of the partition in the HSM where the Amazon Redshift clusters will store their database encryption keys.
        schema:
          type: string
          maxLength: 2147483647
      - name: HsmPartitionPassword
        in: query
        required: true
        description: The password required to access the HSM partition.
        schema:
          type: string
          maxLength: 2147483647
      - name: HsmServerPublicCertificate
        in: query
        required: true
        description: The HSMs public certificate file. When using Cloud HSM, the file name is server.pem.
        schema:
          type: string
          maxLength: 2147483647
      - name: Tags
        in: query
        required: false
        description: A list of tag instances.
        schema:
          type: array
          items:
            allOf:
            - $ref: '#/components/schemas/Tag'
            - xml:
                name: Tag
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - CreateHsmConfiguration
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Create Hsm Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=CreateHsmConfiguration'
    post:
      x-aws-operation-name: CreateHsmConfiguration
      operationId: POST_CreateHsmConfiguration
      description: <p>Creates an HSM configuration that contains the information required by an Amazon Redshift cluster to store and use database encryption keys in a Hardware Security Module (HSM). After creating the HSM configuration, you can specify it as a parameter when creating a cluster. The cluster will then store its encryption keys in the HSM.</p> <p>In addition to creating an HSM configuration, you must also create an HSM client certificate. For more information, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-HSM.html">Hardware Security Modules</a> in the Amazon Redshift Cluster Management Guide.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/CreateHsmConfigurationResult'
        '480':
          description: HsmConfigurationAlreadyExistsFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/HsmConfigurationAlreadyExistsFault'
        '481':
          description: HsmConfigurationQuotaExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/HsmConfigurationQuotaExceededFault'
        '482':
          description: TagLimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/TagLimitExceededFault'
        '483':
          description: InvalidTagFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidTagFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/CreateHsmConfigurationMessage'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - CreateHsmConfiguration
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Create Hsm Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=CreateHsmConfiguration'
components:
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  schemas:
    CreateHsmConfigurationMessage:
      type: object
      required:
      - HsmConfigurationIdentifier
      - Description
      - HsmIpAddress
      - HsmPartitionName
      - HsmPartitionPassword
      - HsmServerPublicCertificate
      title: CreateHsmConfigurationMessage
      properties:
        HsmConfigurationIdentifier:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The identifier to be assigned to the new Amazon Redshift HSM configuration.
        Description:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A text description of the HSM configuration to be created.
        HsmIpAddress:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The IP address that the Amazon Redshift cluster must use to access the HSM.
        HsmPartitionName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the partition in the HSM where the Amazon Redshift clusters will store their database encryption keys.
        HsmPartitionPassword:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The password required to access the HSM partition.
        HsmServerPublicCertificate:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The HSMs public certificate file. When using Cloud HSM, the file name is server.pem.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: A list of tag instances.
      description: <p/>
    String:
      type: string
      maxLength: 2147483647
    Tag:
      type: object
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The key, or name, for the resource tag.
        Value:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The value for the resource tag.
      description: A tag consisting of a name/value pair for a resource.
    HsmConfiguration:
      type: object
      properties:
        HsmConfigurationIdentifier:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the Amazon Redshift HSM configuration.
        Description:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A text description of the HSM configuration.
        HsmIpAddress:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The IP address that the Amazon Redshift cluster must use to access the HSM.
        HsmPartitionName:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the partition in the HSM where the Amazon Redshift clusters will store their database encryption keys.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: The list of tags for the HSM configuration.
      description: Returns information about an HSM configuration, which is an object that describes to Amazon Redshift clusters the information they require to connect to an HSM where they can store database encryption keys.
    TagLimitExceededFault: {}
    InvalidTagFault: {}
    TagList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/Tag'
        - xml:
            name: Tag
    HsmConfigurationQuotaExceededFault: {}
    HsmConfigurationAlreadyExistsFault: {}
    CreateHsmConfigurationResult:
      type: object
      properties:
        HsmConfiguration:
          $ref: '#/components/schemas/HsmConfiguration'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
