openapi: 3.0.0
info:
  version: '2019-12-20'
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=DescribeOrderableClusterOptions API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=DescribeOrderableClusterOptions'
paths:
  /#Action=DescribeOrderableClusterOptions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: DescribeOrderableClusterOptions
      operationId: GET_DescribeOrderableClusterOptions
      description: Returns a list of orderable cluster options. Before you create a new cluster you can use this operation to find what options are available, such as the EC2 Availability Zones (AZ) in the specific Amazon Web Services Region that you can specify, and the node types you can request. The node types differ by available storage, memory, CPU and price. With the cost involved you might want to obtain a list of cluster options in the specific region and specify values when creating a cluster. For more information about managing clusters, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html">Amazon Redshift Clusters</a> in the <i>Amazon Redshift Cluster Management Guide</i>.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/OrderableClusterOptionsMessage'
      parameters:
      - name: ClusterVersion
        in: query
        required: false
        description: '<p>The version filter value. Specify this parameter to show only the available offerings matching the specified version.</p> <p>Default: All versions.</p> <p>Constraints: Must be one of the version returned from <a>DescribeClusterVersions</a>.</p>'
        schema:
          type: string
          maxLength: 2147483647
      - name: NodeType
        in: query
        required: false
        description: The node type filter value. Specify this parameter to show only the available offerings matching the specified node type.
        schema:
          type: string
          maxLength: 2147483647
      - name: MaxRecords
        in: query
        required: false
        description: '<p>The maximum number of response records to return in each call. If the number of remaining response records exceeds the specified <code>MaxRecords</code> value, a value is returned in a <code>marker</code> field of the response. You can retrieve the next set of records by retrying the command with the returned marker value. </p> <p>Default: <code>100</code> </p> <p>Constraints: minimum 20, maximum 100.</p>'
        schema:
          type: integer
      - name: Marker
        in: query
        required: false
        description: 'An optional parameter that specifies the starting point to return a set of response records. When the results of a <a>DescribeOrderableClusterOptions</a> request exceed the value specified in <code>MaxRecords</code>, Amazon Web Services returns a value in the <code>Marker</code> field of the response. You can retrieve the next set of response records by providing the returned marker value in the <code>Marker</code> parameter and retrying the request. '
        schema:
          type: string
          maxLength: 2147483647
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DescribeOrderableClusterOptions
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Describe Orderable Cluster Options
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DescribeOrderableClusterOptions'
    post:
      x-aws-operation-name: DescribeOrderableClusterOptions
      operationId: POST_DescribeOrderableClusterOptions
      description: Returns a list of orderable cluster options. Before you create a new cluster you can use this operation to find what options are available, such as the EC2 Availability Zones (AZ) in the specific Amazon Web Services Region that you can specify, and the node types you can request. The node types differ by available storage, memory, CPU and price. With the cost involved you might want to obtain a list of cluster options in the specific region and specify values when creating a cluster. For more information about managing clusters, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html">Amazon Redshift Clusters</a> in the <i>Amazon Redshift Cluster Management Guide</i>.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/OrderableClusterOptionsMessage'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/DescribeOrderableClusterOptionsMessage'
      parameters:
      - name: MaxRecords
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: Marker
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DescribeOrderableClusterOptions
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Describe Orderable Cluster Options
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DescribeOrderableClusterOptions'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    SupportedPlatformsList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/SupportedPlatform'
        - xml:
            name: SupportedPlatform
    AvailabilityZoneList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/AvailabilityZone'
        - xml:
            name: AvailabilityZone
    IntegerOptional:
      type: integer
    SupportedPlatform:
      type: object
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p/>
      description: A list of supported platforms for orderable clusters.
    AvailabilityZone:
      type: object
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the availability zone.
        SupportedPlatforms:
          allOf:
          - $ref: '#/components/schemas/SupportedPlatformsList'
          - description: <p/>
      description: Describes an availability zone.
    OrderableClusterOptionsList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/OrderableClusterOption'
        - xml:
            name: OrderableClusterOption
    DescribeOrderableClusterOptionsMessage:
      type: object
      title: DescribeOrderableClusterOptionsMessage
      properties:
        ClusterVersion:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p>The version filter value. Specify this parameter to show only the available offerings matching the specified version.</p> <p>Default: All versions.</p> <p>Constraints: Must be one of the version returned from <a>DescribeClusterVersions</a>.</p>'
        NodeType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The node type filter value. Specify this parameter to show only the available offerings matching the specified node type.
        MaxRecords:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: '<p>The maximum number of response records to return in each call. If the number of remaining response records exceeds the specified <code>MaxRecords</code> value, a value is returned in a <code>marker</code> field of the response. You can retrieve the next set of records by retrying the command with the returned marker value. </p> <p>Default: <code>100</code> </p> <p>Constraints: minimum 20, maximum 100.</p>'
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'An optional parameter that specifies the starting point to return a set of response records. When the results of a <a>DescribeOrderableClusterOptions</a> request exceed the value specified in <code>MaxRecords</code>, Amazon Web Services returns a value in the <code>Marker</code> field of the response. You can retrieve the next set of response records by providing the returned marker value in the <code>Marker</code> parameter and retrying the request. '
      description: <p/>
    OrderableClusterOptionsMessage:
      type: object
      properties:
        OrderableClusterOptions:
          allOf:
          - $ref: '#/components/schemas/OrderableClusterOptionsList'
          - description: An <code>OrderableClusterOption</code> structure containing information about orderable options for the cluster.
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'A value that indicates the starting point for the next set of response records in a subsequent request. If a value is returned in a response, you can retrieve the next set of records by providing this returned marker value in the <code>Marker</code> parameter and retrying the command. If the <code>Marker</code> field is empty, all response records have been retrieved for the request. '
      description: 'Contains the output from the <a>DescribeOrderableClusterOptions</a> action. '
    String:
      type: string
      maxLength: 2147483647
    OrderableClusterOption:
      type: object
      properties:
        ClusterVersion:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The version of the orderable cluster.
        ClusterType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'The cluster type, for example <code>multi-node</code>. '
        NodeType:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The node type for the orderable cluster.
        AvailabilityZones:
          allOf:
          - $ref: '#/components/schemas/AvailabilityZoneList'
          - description: A list of availability zones for the orderable cluster.
      description: Describes an orderable cluster option.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
