openapi: 3.0.0
info:
  version: '2019-12-20'
  x-release: v4
  title: 'Redshift Data API Service #Action=AcceptReservedNodeExchange #Action=AcceptReservedNodeExchange #Action=DescribeClusterVersions API'
  description: <p>You can use the Amazon Redshift Data API to run queries on Amazon Redshift tables. You can run SQL statements, which are committed if the statement succeeds. </p> <p>For more information about the Amazon Redshift Data API and CLI usage examples, see <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html">Using the Amazon Redshift Data API</a> in the <i>Amazon Redshift Management Guide</i>. </p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: redshift-data
  x-aws-signingName: redshift-data
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/redshift-data-2019-12-20.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: https://redshift-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Redshift Data API Service multi-region endpoint
- url: http://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
- url: https://redshift-data.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Redshift Data API Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=DescribeClusterVersions'
paths:
  /#Action=DescribeClusterVersions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: DescribeClusterVersions
      operationId: GET_DescribeClusterVersions
      description: Returns descriptions of the available Amazon Redshift cluster versions. You can call this operation even before creating any clusters to learn more about the Amazon Redshift versions. For more information about managing clusters, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html">Amazon Redshift Clusters</a> in the <i>Amazon Redshift Cluster Management Guide</i>.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterVersionsMessage'
      parameters:
      - name: ClusterVersion
        in: query
        required: false
        description: '<p>The specific cluster version to return.</p> <p>Example: <code>1.0</code> </p>'
        schema:
          type: string
          maxLength: 2147483647
      - name: ClusterParameterGroupFamily
        in: query
        required: false
        description: <p>The name of a specific cluster parameter group family to return details for.</p> <p>Constraints:</p> <ul> <li> <p>Must be 1 to 255 alphanumeric characters</p> </li> <li> <p>First character must be a letter</p> </li> <li> <p>Cannot end with a hyphen or contain two consecutive hyphens</p> </li> </ul>
        schema:
          type: string
          maxLength: 2147483647
      - name: MaxRecords
        in: query
        required: false
        description: '<p>The maximum number of response records to return in each call. If the number of remaining response records exceeds the specified <code>MaxRecords</code> value, a value is returned in a <code>marker</code> field of the response. You can retrieve the next set of records by retrying the command with the returned marker value. </p> <p>Default: <code>100</code> </p> <p>Constraints: minimum 20, maximum 100.</p>'
        schema:
          type: integer
      - name: Marker
        in: query
        required: false
        description: 'An optional parameter that specifies the starting point to return a set of response records. When the results of a <a>DescribeClusterVersions</a> request exceed the value specified in <code>MaxRecords</code>, Amazon Web Services returns a value in the <code>Marker</code> field of the response. You can retrieve the next set of response records by providing the returned marker value in the <code>Marker</code> parameter and retrying the request. '
        schema:
          type: string
          maxLength: 2147483647
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DescribeClusterVersions
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - G E T_ Describe Cluster Versions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DescribeClusterVersions'
    post:
      x-aws-operation-name: DescribeClusterVersions
      operationId: POST_DescribeClusterVersions
      description: Returns descriptions of the available Amazon Redshift cluster versions. You can call this operation even before creating any clusters to learn more about the Amazon Redshift versions. For more information about managing clusters, go to <a href="https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html">Amazon Redshift Clusters</a> in the <i>Amazon Redshift Cluster Management Guide</i>.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ClusterVersionsMessage'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/DescribeClusterVersionsMessage'
      parameters:
      - name: MaxRecords
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: Marker
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DescribeClusterVersions
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - '2012-12-01'
      summary: Amazon Redshift - P O S T_ Describe Cluster Versions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DescribeClusterVersions'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    DescribeClusterVersionsMessage:
      type: object
      title: DescribeClusterVersionsMessage
      properties:
        ClusterVersion:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: '<p>The specific cluster version to return.</p> <p>Example: <code>1.0</code> </p>'
        ClusterParameterGroupFamily:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: <p>The name of a specific cluster parameter group family to return details for.</p> <p>Constraints:</p> <ul> <li> <p>Must be 1 to 255 alphanumeric characters</p> </li> <li> <p>First character must be a letter</p> </li> <li> <p>Cannot end with a hyphen or contain two consecutive hyphens</p> </li> </ul>
        MaxRecords:
          allOf:
          - $ref: '#/components/schemas/IntegerOptional'
          - description: '<p>The maximum number of response records to return in each call. If the number of remaining response records exceeds the specified <code>MaxRecords</code> value, a value is returned in a <code>marker</code> field of the response. You can retrieve the next set of records by retrying the command with the returned marker value. </p> <p>Default: <code>100</code> </p> <p>Constraints: minimum 20, maximum 100.</p>'
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'An optional parameter that specifies the starting point to return a set of response records. When the results of a <a>DescribeClusterVersions</a> request exceed the value specified in <code>MaxRecords</code>, Amazon Web Services returns a value in the <code>Marker</code> field of the response. You can retrieve the next set of response records by providing the returned marker value in the <code>Marker</code> parameter and retrying the request. '
      description: <p/>
    ClusterVersionsMessage:
      type: object
      properties:
        Marker:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: 'A value that indicates the starting point for the next set of response records in a subsequent request. If a value is returned in a response, you can retrieve the next set of records by providing this returned marker value in the <code>Marker</code> parameter and retrying the command. If the <code>Marker</code> field is empty, all response records have been retrieved for the request. '
        ClusterVersions:
          allOf:
          - $ref: '#/components/schemas/ClusterVersionList'
          - description: 'A list of <code>Version</code> elements. '
      description: 'Contains the output from the <a>DescribeClusterVersions</a> action. '
    IntegerOptional:
      type: integer
    ClusterVersionList:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/ClusterVersion'
        - xml:
            name: ClusterVersion
    String:
      type: string
      maxLength: 2147483647
    ClusterVersion:
      type: object
      properties:
        ClusterVersion:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The version number used by the cluster.
        ClusterParameterGroupFamily:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The name of the cluster parameter group family for the cluster.
        Description:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The description of the cluster version.
      description: Describes a cluster version, including the parameter group family and description of the version.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/redshift-data/
x-hasEquivalentPaths: true
